class GetEnterprises {
  final enterprises = [
    {
      "CodigoInterno_Empresa": 2,
      "Codigo_Empresa": "01",
      "Nome_Empresa": "Deposito de Meias São José",
      "NomeFantasia_Empresa": "São José",
      "Cnpj_Empresa": "01150157000166",
      "InscricaoEstadual_Empresa": "114630883118",
      "CCM_Empresa": "2",
      "FlagInterna_Empresa": 0,
      "CodigoInterno_PoliticaPreco": null,
      "FlagVarejo_Empresa": 1,
      "FlagAtacado_Empresa": 1,
      "FlagECommerce_Empresa": 1,
      "FlagCentroDistribuicao_Empresa": 0,
      "FlagDepositoCentral_Empresa": 0,
      "FlagLoja_Empresa": 1,
      "FlagServicos_Empresa": 0,
      "CodigoAreaTel1_Empresa": "11",
      "CodigoAreaTel2_Empresa": "",
      "CodigoAreaTel3_Empresa": "",
      "Cep_Empresa": "07047020",
      "Logradouro_Empresa": "Rua Dr Braulio Gomes",
      "NumEndereco_Empresa": "141",
      "Complemento_Empresa": "1º Andar",
      "Referencia_Empresa": null,
      "Bairro_Empresa": "República",
      "Cidade_Empresa": "São Paulo",
      "Estado_Empresa": "SP",
      "CepEntrega_Empresa": "01047020",
      "LogradouroEntrega_Empresa": "Rua Dr Braulio Gomes",
      "NumEnderecoEntrega_Empresa": "141",
      "ComplementoEntrega_Empresa": "",
      "ReferenciaEntrega_Empresa": null,
      "BairroEntrega_Empresa": "República",
      "CidadeEntrega_Empresa": "São Paulo",
      "EstadoEntrega_Empresa": "SP",
      "CepCobranca_Empresa": "01047020",
      "LogradouroCobranca_Empresa": "Rua Dr Braulio Gomes",
      "NumEnderecoCobranca_Empresa": "141",
      "ComplementoCobranca_Empresa": "",
      "ReferenciaCobranca_Empresa": null,
      "BairroCobranca_Empresa": "República",
      "CidadeCobranca_Empresa": "São Paulo",
      "EstadoCobranca_Empresa": "SP",
      "Telefone1_Empresa": "3125-6767",
      "Telefone2_Empresa": "",
      "Telefone3_Empresa": "",
      "CodigoInterno_RamoAtividade": 1,
      "FlagMeEpp_Empresa": 1,
      "FlagSimplesFederal_Empresa": 2,
      "Codigo_SimpNacFai": 7,
      "FlagIcmsSobreFrete_Empresa": 0,
      "FlagIcmsSobreEncFinan_Empresa": 0,
      "FlagUsaTotProdLiqNaNf_Empresa": 0,
      "FlagIPISobreValBruto_Empresa": 0,
      "FlagIPISobreFrete_Empresa": 0,
      "FlagIcmsSobreIpi_Empresa": 0,
      "FlagImprimeCredSubstNaNf_Empresa": 1,
      "FlagIPISobreEncFinan_Empresa": 0,
      "FlagIcmsSubstTitFinanFatorRepr_Empresa": 1,
      "FlagIpiCompoeTitFinanFatorRepr_Empresa": 1,
      "FlagIcmsSubstSobreDespAces_Empresa": 0,
      "NomeContato_Empresa": null,
      "SenhaMensal_Empresa": "4600748448748WR120449684",
      "MensagemErroSenhaMensal_Empresa": null,
      "FlagTipoArredondamento_Empresa": 1,
      "FlagTipoFrete_Empresa": "CIF",
      "EMail_Empresa": "",
      "EnderecoEletronico_Empresa": null,
      "CodigoSuframa_Empresa": null,
      "FlagTipoRegime_Empresa": 3,
      "FlagIpiInclusoPrecoVenda_Empresa": 1,
      "FlagTermoAcordoRegimeEspecialAtacado_Empresa": 0,
      "FlagReduzirIcmsEntradaInterestadual_Empresa": 0,
      "Codigo_MuniIBGE": "3550308",
      "Codigo_MuniIBGEEntrega": "3550308",
      "Codigo_MuniIBGECobranca": "3550308",
      "FlagConsidDifIcmsEntrInterestComoOutrosDebitos_Empresa": 0,
      "ICMSSimpNacAliq_Empresa": 1.44,
      "AccountTreasuryCodePrincipal": null,
      "IsMainEnterpriseWithBranchs": 1,
      "HaveAuthorizationProcessSaleRequestProductMinimumPrice": true,
      "FlagImprimeCredSubstRetNaNf_Empresa": 0,
      "FlagConsideraIcmsCalcBasePisCofins_Empresa": 0
    },
    {
      "CodigoInterno_Empresa": 3,
      "Codigo_Empresa": "02",
      "Nome_Empresa": "Deposito loja 1",
      "NomeFantasia_Empresa": "Deposito loja 1",
      "Cnpj_Empresa": "01150157000247",
      "InscricaoEstadual_Empresa": "114716120113",
      "CCM_Empresa": "3",
      "FlagInterna_Empresa": 0,
      "CodigoInterno_PoliticaPreco": null,
      "FlagVarejo_Empresa": 1,
      "FlagAtacado_Empresa": 1,
      "FlagECommerce_Empresa": 1,
      "FlagCentroDistribuicao_Empresa": 0,
      "FlagDepositoCentral_Empresa": 0,
      "FlagLoja_Empresa": 1,
      "FlagServicos_Empresa": 0,
      "CodigoAreaTel1_Empresa": "11",
      "CodigoAreaTel2_Empresa": "",
      "CodigoAreaTel3_Empresa": "",
      "Cep_Empresa": "01047020",
      "Logradouro_Empresa": "Rua Dr Braulio Gomes",
      "NumEndereco_Empresa": "222",
      "Complemento_Empresa": "",
      "Referencia_Empresa": null,
      "Bairro_Empresa": "Republica",
      "Cidade_Empresa": "São Paulo",
      "Estado_Empresa": "SP",
      "CepEntrega_Empresa": "01047020",
      "LogradouroEntrega_Empresa": "Rua Doutor Bráulio Gomes",
      "NumEnderecoEntrega_Empresa": "222",
      "ComplementoEntrega_Empresa": "",
      "ReferenciaEntrega_Empresa": null,
      "BairroEntrega_Empresa": "República",
      "CidadeEntrega_Empresa": "São Paulo",
      "EstadoEntrega_Empresa": "SP",
      "CepCobranca_Empresa": "01047020",
      "LogradouroCobranca_Empresa": "Rua Doutor Bráulio Gomes",
      "NumEnderecoCobranca_Empresa": "222",
      "ComplementoCobranca_Empresa": "",
      "ReferenciaCobranca_Empresa": null,
      "BairroCobranca_Empresa": "República",
      "CidadeCobranca_Empresa": "São Paulo",
      "EstadoCobranca_Empresa": "SP",
      "Telefone1_Empresa": "3215-6767",
      "Telefone2_Empresa": "",
      "Telefone3_Empresa": "",
      "CodigoInterno_RamoAtividade": 1,
      "FlagMeEpp_Empresa": 0,
      "FlagSimplesFederal_Empresa": 0,
      "Codigo_SimpNacFai": null,
      "FlagIcmsSobreFrete_Empresa": 0,
      "FlagIcmsSobreEncFinan_Empresa": 0,
      "FlagUsaTotProdLiqNaNf_Empresa": 0,
      "FlagIPISobreValBruto_Empresa": 0,
      "FlagIPISobreFrete_Empresa": 0,
      "FlagIcmsSobreIpi_Empresa": 0,
      "FlagImprimeCredSubstNaNf_Empresa": 0,
      "FlagIPISobreEncFinan_Empresa": 0,
      "FlagIcmsSubstTitFinanFatorRepr_Empresa": 0,
      "FlagIpiCompoeTitFinanFatorRepr_Empresa": 0,
      "FlagIcmsSubstSobreDespAces_Empresa": 0,
      "NomeContato_Empresa": null,
      "SenhaMensal_Empresa": "4600748449072WR120449684",
      "MensagemErroSenhaMensal_Empresa": null,
      "FlagTipoArredondamento_Empresa": 1,
      "FlagTipoFrete_Empresa": "CIF",
      "EMail_Empresa": "",
      "EnderecoEletronico_Empresa": null,
      "CodigoSuframa_Empresa": null,
      "FlagTipoRegime_Empresa": 3,
      "FlagIpiInclusoPrecoVenda_Empresa": 0,
      "FlagTermoAcordoRegimeEspecialAtacado_Empresa": 0,
      "FlagReduzirIcmsEntradaInterestadual_Empresa": 0,
      "Codigo_MuniIBGE": "3550308",
      "Codigo_MuniIBGEEntrega": "3550308",
      "Codigo_MuniIBGECobranca": "3550308",
      "FlagConsidDifIcmsEntrInterestComoOutrosDebitos_Empresa": 0,
      "ICMSSimpNacAliq_Empresa": 0.00,
      "AccountTreasuryCodePrincipal": null,
      "IsMainEnterpriseWithBranchs": 0,
      "HaveAuthorizationProcessSaleRequestProductMinimumPrice": false,
      "FlagImprimeCredSubstRetNaNf_Empresa": 0,
      "FlagConsideraIcmsCalcBasePisCofins_Empresa": 1
    },
    {
      "CodigoInterno_Empresa": 4,
      "Codigo_Empresa": "03",
      "Nome_Empresa": "Terceira empresa",
      "NomeFantasia_Empresa": "3th enterprise",
      "Cnpj_Empresa": "10347996000160",
      "InscricaoEstadual_Empresa": "148298358119",
      "CCM_Empresa": "4",
      "FlagInterna_Empresa": 0,
      "CodigoInterno_PoliticaPreco": null,
      "FlagVarejo_Empresa": 1,
      "FlagAtacado_Empresa": 1,
      "FlagECommerce_Empresa": 1,
      "FlagCentroDistribuicao_Empresa": 0,
      "FlagDepositoCentral_Empresa": 0,
      "FlagLoja_Empresa": 1,
      "FlagServicos_Empresa": 0,
      "CodigoAreaTel1_Empresa": "11",
      "CodigoAreaTel2_Empresa": "",
      "CodigoAreaTel3_Empresa": "",
      "Cep_Empresa": "07047020",
      "Logradouro_Empresa": "Rua Dr Braulio Gomes",
      "NumEndereco_Empresa": "141",
      "Complemento_Empresa": "",
      "Referencia_Empresa": null,
      "Bairro_Empresa": "República",
      "Cidade_Empresa": "São Paulo",
      "Estado_Empresa": "SP",
      "CepEntrega_Empresa": "01047020",
      "LogradouroEntrega_Empresa": "Rua Dr Braulio Gomes",
      "NumEnderecoEntrega_Empresa": "141",
      "ComplementoEntrega_Empresa": "",
      "ReferenciaEntrega_Empresa": null,
      "BairroEntrega_Empresa": "República",
      "CidadeEntrega_Empresa": "São Paulo",
      "EstadoEntrega_Empresa": "SP",
      "CepCobranca_Empresa": "01047020",
      "LogradouroCobranca_Empresa": "Rua Dr Braulio Gomes",
      "NumEnderecoCobranca_Empresa": "141",
      "ComplementoCobranca_Empresa": "",
      "ReferenciaCobranca_Empresa": null,
      "BairroCobranca_Empresa": "República",
      "CidadeCobranca_Empresa": "São Paulo",
      "EstadoCobranca_Empresa": "SP",
      "Telefone1_Empresa": "3125-6767",
      "Telefone2_Empresa": "",
      "Telefone3_Empresa": "",
      "CodigoInterno_RamoAtividade": 1,
      "FlagMeEpp_Empresa": 1,
      "FlagSimplesFederal_Empresa": 0,
      "Codigo_SimpNacFai": null,
      "FlagIcmsSobreFrete_Empresa": 0,
      "FlagIcmsSobreEncFinan_Empresa": 0,
      "FlagUsaTotProdLiqNaNf_Empresa": 0,
      "FlagIPISobreValBruto_Empresa": 0,
      "FlagIPISobreFrete_Empresa": 0,
      "FlagIcmsSobreIpi_Empresa": 0,
      "FlagImprimeCredSubstNaNf_Empresa": 1,
      "FlagIPISobreEncFinan_Empresa": 0,
      "FlagIcmsSubstTitFinanFatorRepr_Empresa": 1,
      "FlagIpiCompoeTitFinanFatorRepr_Empresa": 1,
      "FlagIcmsSubstSobreDespAces_Empresa": 0,
      "NomeContato_Empresa": null,
      "SenhaMensal_Empresa": "41392104448724WR120449684",
      "MensagemErroSenhaMensal_Empresa": null,
      "FlagTipoArredondamento_Empresa": 1,
      "FlagTipoFrete_Empresa": "CIF",
      "EMail_Empresa": "",
      "EnderecoEletronico_Empresa": null,
      "CodigoSuframa_Empresa": null,
      "FlagTipoRegime_Empresa": 1,
      "FlagIpiInclusoPrecoVenda_Empresa": 1,
      "FlagTermoAcordoRegimeEspecialAtacado_Empresa": 0,
      "FlagReduzirIcmsEntradaInterestadual_Empresa": 0,
      "Codigo_MuniIBGE": "3550308",
      "Codigo_MuniIBGEEntrega": "3550308",
      "Codigo_MuniIBGECobranca": "3550308",
      "FlagConsidDifIcmsEntrInterestComoOutrosDebitos_Empresa": 0,
      "ICMSSimpNacAliq_Empresa": 0.00,
      "AccountTreasuryCodePrincipal": null,
      "IsMainEnterpriseWithBranchs": 0,
      "HaveAuthorizationProcessSaleRequestProductMinimumPrice": false,
      "FlagImprimeCredSubstRetNaNf_Empresa": 0,
      "FlagConsideraIcmsCalcBasePisCofins_Empresa": 0
    },
    {
      "CodigoInterno_Empresa": 5,
      "Codigo_Empresa": "04",
      "Nome_Empresa": "Jundipar Razão Social",
      "NomeFantasia_Empresa": "Jundipar",
      "Cnpj_Empresa": "50975853000117",
      "InscricaoEstadual_Empresa": "407008854111",
      "CCM_Empresa": "5",
      "FlagInterna_Empresa": 0,
      "CodigoInterno_PoliticaPreco": null,
      "FlagVarejo_Empresa": 1,
      "FlagAtacado_Empresa": 1,
      "FlagECommerce_Empresa": 1,
      "FlagCentroDistribuicao_Empresa": 0,
      "FlagDepositoCentral_Empresa": 0,
      "FlagLoja_Empresa": 1,
      "FlagServicos_Empresa": 0,
      "CodigoAreaTel1_Empresa": "11",
      "CodigoAreaTel2_Empresa": "",
      "CodigoAreaTel3_Empresa": "",
      "Cep_Empresa": "07047020",
      "Logradouro_Empresa": "Rua Dr Braulio Gomes",
      "NumEndereco_Empresa": "141",
      "Complemento_Empresa": "1º Andar",
      "Referencia_Empresa": null,
      "Bairro_Empresa": "República",
      "Cidade_Empresa": "São Paulo",
      "Estado_Empresa": "SP",
      "CepEntrega_Empresa": "01047020",
      "LogradouroEntrega_Empresa": "Rua Dr Braulio Gomes",
      "NumEnderecoEntrega_Empresa": "141",
      "ComplementoEntrega_Empresa": "",
      "ReferenciaEntrega_Empresa": null,
      "BairroEntrega_Empresa": "República",
      "CidadeEntrega_Empresa": "São Paulo",
      "EstadoEntrega_Empresa": "SP",
      "CepCobranca_Empresa": "01047020",
      "LogradouroCobranca_Empresa": "Rua Dr Braulio Gomes",
      "NumEnderecoCobranca_Empresa": "141",
      "ComplementoCobranca_Empresa": "",
      "ReferenciaCobranca_Empresa": null,
      "BairroCobranca_Empresa": "República",
      "CidadeCobranca_Empresa": "São Paulo",
      "EstadoCobranca_Empresa": "SP",
      "Telefone1_Empresa": "3125-6767",
      "Telefone2_Empresa": "",
      "Telefone3_Empresa": "",
      "CodigoInterno_RamoAtividade": 1,
      "FlagMeEpp_Empresa": 1,
      "FlagSimplesFederal_Empresa": 0,
      "Codigo_SimpNacFai": null,
      "FlagIcmsSobreFrete_Empresa": 0,
      "FlagIcmsSobreEncFinan_Empresa": 0,
      "FlagUsaTotProdLiqNaNf_Empresa": 0,
      "FlagIPISobreValBruto_Empresa": 0,
      "FlagIPISobreFrete_Empresa": 0,
      "FlagIcmsSobreIpi_Empresa": 0,
      "FlagImprimeCredSubstNaNf_Empresa": 1,
      "FlagIPISobreEncFinan_Empresa": 0,
      "FlagIcmsSubstTitFinanFatorRepr_Empresa": 1,
      "FlagIpiCompoeTitFinanFatorRepr_Empresa": 1,
      "FlagIcmsSubstSobreDespAces_Empresa": 0,
      "NomeContato_Empresa": null,
      "SenhaMensal_Empresa": "203903532448552WR120449684",
      "MensagemErroSenhaMensal_Empresa": null,
      "FlagTipoArredondamento_Empresa": 1,
      "FlagTipoFrete_Empresa": "CIF",
      "EMail_Empresa": "",
      "EnderecoEletronico_Empresa": null,
      "CodigoSuframa_Empresa": null,
      "FlagTipoRegime_Empresa": 3,
      "FlagIpiInclusoPrecoVenda_Empresa": 1,
      "FlagTermoAcordoRegimeEspecialAtacado_Empresa": 0,
      "FlagReduzirIcmsEntradaInterestadual_Empresa": 0,
      "Codigo_MuniIBGE": "3550308",
      "Codigo_MuniIBGEEntrega": "3550308",
      "Codigo_MuniIBGECobranca": "3550308",
      "FlagConsidDifIcmsEntrInterestComoOutrosDebitos_Empresa": 0,
      "ICMSSimpNacAliq_Empresa": 0.00,
      "AccountTreasuryCodePrincipal": null,
      "IsMainEnterpriseWithBranchs": 0,
      "HaveAuthorizationProcessSaleRequestProductMinimumPrice": false,
      "FlagImprimeCredSubstRetNaNf_Empresa": 0,
      "FlagConsideraIcmsCalcBasePisCofins_Empresa": 0
    }
  ];
}
