class GetInventoryFrozenProcess {
  final List inventoryFrozenProcess = [
    {
      "CodigoInterno_Inventario": 3,
      "NumeroContagensIguais_Inventario": null,
      "CodigoInterno_Empresa": 2,
      "CodigoInterno_Funcionario": 2,
      "FlagAjuste_Inventario": 0,
      "DataCriacao_Inventario": "2021-12-06T10:50:48",
      "DataCongelamento_Inventario": "2021-12-06T10:54:00",
      "Obs_Inventario": null,
      "ExisteProdutoSemCusto": 1,
      "CodigoInterno_TipoEstoque": 1,
      "CodigoInterno_Empresa1": 2,
      "Codigo_Empresa": "01",
      "Nome_Empresa": "Deposito de Meias São José",
      "NomeFantasia_Empresa": "São José",
      "Cnpj_Empresa": "01150157000166",
      "InscricaoEstadual_Empresa": "114630883118",
      "CCM_Empresa": "2",
      "FlagInterna_Empresa": 0,
      "CodigoInterno_PoliticaPreco": null,
      "FlagVarejo_Empresa": 1,
      "FlagAtacado_Empresa": 1,
      "FlagECommerce_Empresa": 1,
      "FlagCentroDistribuicao_Empresa": 0,
      "FlagDepositoCentral_Empresa": 0,
      "FlagLoja_Empresa": 1,
      "FlagServicos_Empresa": 0,
      "CodigoAreaTel1_Empresa": "11",
      "CodigoAreaTel2_Empresa": "",
      "CodigoAreaTel3_Empresa": "",
      "Cep_Empresa": "07047020",
      "Logradouro_Empresa": "Rua Dr Braulio Gomes",
      "NumEndereco_Empresa": "141",
      "Complemento_Empresa": "1º Andar",
      "Referencia_Empresa": null,
      "Bairro_Empresa": "República",
      "Cidade_Empresa": "São Paulo",
      "Estado_Empresa": "SP",
      "CepEntrega_Empresa": "01047020",
      "LogradouroEntrega_Empresa": "Rua Dr Braulio Gomes",
      "NumEnderecoEntrega_Empresa": "141",
      "ComplementoEntrega_Empresa": "",
      "ReferenciaEntrega_Empresa": null,
      "BairroEntrega_Empresa": "República",
      "CidadeEntrega_Empresa": "São Paulo",
      "EstadoEntrega_Empresa": "SP",
      "CepCobranca_Empresa": "01047020",
      "LogradouroCobranca_Empresa": "Rua Dr Braulio Gomes",
      "NumEnderecoCobranca_Empresa": "141",
      "ComplementoCobranca_Empresa": "",
      "ReferenciaCobranca_Empresa": null,
      "BairroCobranca_Empresa": "República",
      "CidadeCobranca_Empresa": "São Paulo",
      "EstadoCobranca_Empresa": "SP",
      "Telefone1_Empresa": "3125-6767",
      "Telefone2_Empresa": "",
      "Telefone3_Empresa": "",
      "CodigoInterno_RamoAtividade": 1,
      "FlagMeEpp_Empresa": 1,
      "FlagSimplesFederal_Empresa": 2,
      "Codigo_SimpNacFai": 7,
      "FlagIcmsSobreFrete_Empresa": 0,
      "FlagIcmsSobreEncFinan_Empresa": 0,
      "FlagUsaTotProdLiqNaNf_Empresa": 0,
      "FlagIPISobreValBruto_Empresa": 0,
      "FlagIPISobreFrete_Empresa": 0,
      "FlagIcmsSobreIpi_Empresa": 0,
      "FlagImprimeCredSubstNaNf_Empresa": 1,
      "FlagIPISobreEncFinan_Empresa": 0,
      "FlagIcmsSubstTitFinanFatorRepr_Empresa": 1,
      "FlagIpiCompoeTitFinanFatorRepr_Empresa": 1,
      "FlagIcmsSubstSobreDespAces_Empresa": 0,
      "NomeContato_Empresa": null,
      "SenhaMensal_Empresa": "4600748448748WR120449684",
      "MensagemErroSenhaMensal_Empresa": null,
      "FlagTipoArredondamento_Empresa": 1,
      "FlagTipoFrete_Empresa": "CIF",
      "EMail_Empresa": "",
      "EnderecoEletronico_Empresa": null,
      "CodigoSuframa_Empresa": null,
      "FlagTipoRegime_Empresa": 3,
      "FlagIpiInclusoPrecoVenda_Empresa": 1,
      "FlagTermoAcordoRegimeEspecialAtacado_Empresa": 0,
      "FlagReduzirIcmsEntradaInterestadual_Empresa": 0,
      "Codigo_MuniIBGE": "3550308",
      "Codigo_MuniIBGEEntrega": "3550308",
      "Codigo_MuniIBGECobranca": "3550308",
      "FlagConsidDifIcmsEntrInterestComoOutrosDebitos_Empresa": 0,
      "ICMSSimpNacAliq_Empresa": 1.44,
      "AccountTreasuryCodePrincipal": null,
      "IsMainEnterpriseWithBranchs": 1,
      "HaveAuthorizationProcessSaleRequestProductMinimumPrice": true,
      "FlagImprimeCredSubstRetNaNf_Empresa": 0,
      "FlagConsideraIcmsCalcBasePisCofins_Empresa": 0,
      "CodigoInterno_Funcionario1": 2,
      "EMail_Funcionario": "",
      "FlagVendedor_Funcionario": 1,
      "FlagComprador_Funcionario": 1,
      "DataAdmissao_Funcionario": "2012-02-01T00:00:00",
      "DataNascimento_Funcionario": "1996-05-07T00:00:00",
      "DataDemissao_Funcionario": null,
      "FlagTipoVendedor_Funcionario": "A",
      "RgInscricaoEstadual_Funcionario": "377220048",
      "CpfCnpj_Funcionario": "39367507852",
      "CodigoFuncional_Funcionario": "123",
      "Nome_Funcionario": "Willians Junior",
      "CodigoInterno_GrupoFinanDespesa": null,
      "CodigoInterno_CategFinanDespesa": null,
      "CodigoInterno_SubCategFinanDespesa": null,
      "CodigoInterno_GrupoFinanReceita": null,
      "CodigoInterno_CategFinanReceita": null,
      "CodigoInterno_SubCategFinanReceita": null,
      "CodigoAreaTel1_Funcionario": "",
      "CodigoAreaTel2_Funcionario": "",
      "Telefone1_Funcionario": "",
      "Telefone2_Funcionario": "",
      "Estado_Funcionario": "  ",
      "NumEndereco_Funcionario": null,
      "Cep_Funcionario": "",
      "Cidade_Funcionario": "",
      "Bairro_Funcionario": "",
      "Logradouro_Funcionario": "",
      "Complemento_Funcionario": "",
      "Referencia_Funcionario": null,
      "FlagMotorista_Funcionario": 0,
      "NumeroCnh_Funcionario": null,
      "DataVectoCnh_Funcionario": null,
      "CategoriaCnh_Funcionario": null,
      "Observacoes_Funcionario": null,
      "FlagCodigoFuncionalPersonalizado_Funcionario": 1,
      "FlagOperadorPdv_Funcionario": 1,
      "FlagPagaBanco_Funcionario": 0,
      "CodigoInterno_InstFinan": null,
      "NomeConta_Funcionario": "",
      "AgenciaInstFinan_Funcionario": "",
      "DigitoAgenciaInstFinan_Funcionario": "",
      "NumeroConta_Funcionario": "",
      "DigitoConta_Funcionario": "",
      "CodigoInterno_FormaPagto": null,
      "CodigoInterno_Empresa2": 2,
      "FlagPrestadorServicos_Funcionario": 0,
      "Pis_Funcionario": null,
      "NomeReduzido_Funcionario": "Junior",
      "CodigoInterno_Cargo": null,
      "CodigoInterno_TipoEstoque1": 1,
      "Nome_TipoEstoque": "Estoque Atual",
      "FlagTipo_TipoEstoque": 1,
      "FlagInterno_TipoEstoque": true
    }
  ];
}
